[features]
seeds = true
skip-lint = false

[programs.localnet]
extracto_program = "CHPyHid6CQzErEYrsuinBRsjPdsUZdUzgKMCc6VZ9Tjf"

[programs.devnet]
extracto_program = "CHPyHid6CQzErEYrsuinBRsjPdsUZdUzgKMCc6VZ9Tjf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/tjumma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "3ao63wcSRNa76bncC2M3KupNtXBFiDyNbgK52VG7dLaE"
program = "./program-deps/gpl_session.so"