[features]
seeds = true
skip-lint = false
[programs.localnet]
extracto_program = "2UY7QMKYhhopePhWBU8rorttHRWsijJC4r4T72xxjH6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tjumma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
